### ISSUE TITLE
[UserStory] Creating a name for the product

### ISSUE THREAD

**Issue by CamiJolly1** [Kitchen-Inventory-App-Org/KitchenApp#9]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  developer  
**I want**   a better name for our product,
**so that**  it can have widespread appeal and hold favor to stakeholders 
## Acceptance Criteria

A name that the current teams agrees upon 

## Supporting Information
We are not using a product name, but a product description as of right now. 
### Dependents
N/A

Result: Product name will be called "Pantry Profile"

**Comment by CamiJolly1** [comment]
FlavorFinds
CulinaryCraze
SpoonSavant
PantryPulse
Chef'sChamber
SpiceSavvy
IngredientInsider
CulinaryCupboard
WhiskWizard
RecipeRadar
FridgeFriend
UtensilUtopia
KitchenKarma
FlavorFinder
CulinaryChronicle
DishDomain
StockSavvy
NourishNook
StirItSmart
CulinaryComrade

**Comment by cchum** [comment]
RecipeRadar
DishDiscovery
GourmetGuide
RecipeRealm
RecipeRoundup
CulinaryCraft
KitchenInspire
RecipeRendezvous
DishDelight
KitchenWizard
RecipeRevel
GourmetGenius
CulinaryCreations
RecipeRadar
KitchenQuest
DishDazzler
RecipeRush

**Comment by Ciscoslahs** [comment]
PantryProfile is the name we decided on.
